#!/usr/bin/env bash
#
#  Author:  Jose Lima
#  Date:    2024-01-03 15:25

# if [ -d "tests/" ]; then
#   python3 -m pytest tests/ -v
#   RET=$?
# elif [ -d "priv/" ]; then
#   python3 -m pytest priv/ -v
#   RET=$?
# fi

# if [ $RET -ne 0 ]; then
#   echo "pytest failed"
#   exit 1
# fi

# exit 0


# branch_name=$(git symbolic-ref --short HEAD)
# valid_branch_regex="^(feature|bugfix|patch)/[a-zA-Z0-9._-]+$"

# if ! [[ $branch_name =~ $valid_branch_regex ]]; then
#   echo "invalid branch name, does not meet standards"
#   echo "valid names: $valid_branch_regex"
#   exit 1
# fi 
