font_family      JetBrains Mono Medium
bold_font        JetBrains Mono ExtraBold
italic_font      JetBrains Mono Italic
bold_italic_font JetBrains Mono ExtraBold Italic

font_size 20.0

adjust_line_height 120%

cursor_shape block

window_border_width 0
window_margin_width 0
cursor_blink_interval 0
visual_bell_duration 0
enable_audio_bell no

hide_window_decorations titlebar-only

scrollback_pager_history_size 2

copy_on_select yes

repaint_delay 5

input_delay 1

sync_to_monitor no

tab_title_template "term: {title.lower()}"

background #1e222a
# -> dark background #1c1f26

foreground #afb6c4

selection_foreground #000000

selection_background #afd99a

# black
color0 #282c34
color8 #5f6673

# red
color1 #e06c75
color9 #e06c75

# green
color2 #A3BE8C
color10 #A3BE8C

# yellow
color3  #e5c07b
color11 #e5c07b

# blue
color4  #61afef
color12 #204062

# purple
color5  #c678dd
color13 #c678dd

# cyan
color6  #56b6c2
color14 #56b6c2

# white
color7  #dcdfe4
color15 #dcdfe4

clipboard_control write-clipboard write-primary read-clipboard

macos_option_as_alt yes

macos_quit_when_last_window_closed yes

map cmd+equal            change_font_size all +1.0
map cmd+minus           change_font_size all -1.0
map cmd+0               change_font_size all 0

