alias f='fd -tf'
alias l='less -R '
alias m='more '

alias ga='git add '
alias gap='git add -p '
alias gd='git diff '
alias gds='git diff --staged'
alias gc='git commit '
alias gco='git checkout '
alias gf='git fetch --all'
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gp='git push '
alias gpu='git pull'
alias gr='git reflog '
alias gs='git status '
alias gwa='git worktree add '
alias gwl='git worktree list'
alias gwr='git worktree remove '
