alias f='fd -tf'
alias l='less -R '
alias m='more '

alias gc='git commit '
alias gp='git push '
alias gs='git status '
alias gr='git reflog '
alias gb='git branch '
alias gco='git checkout '
alias gwa='git worktree add '
alias gwr='git worktree remove '
alias gwl='git worktree list'
