# https://docs.helix-editor.com/configuration.html
theme = "mycatppuccin_mocha"

[editor]
true-color = true
mouse = false
line-number = "relative"
bufferline = "multiple"
shell = ["zsh", "-c"]
# color-modes = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "block"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.g]
q = ":reflow"




