[[language]]
name = "ansible"
scope = "source.ansible"
file-types = ["yml", "yaml"]
roots = [".git", "ansible.cfg"]
comment-token = "#"
indent = { tab-width =2, unit = "  "}
language-server = { command = "ansible-language-server", args = ["--stdio"]}












