---
# Author: Jose Lima
# Date: 2023-10-20 12:40 CST

- name: "Boot strap new servers"
  hosts: "!localhost,all"
  gather_facts: false
  # serial: 10

  tasks:
    - name: Copy rc files
      ansible.builtin.template:
        src: ./j2/{{ item }}.j2
        dest: ~/.{{ item }}
        mode: 0644
      loop:
        - vimrc
        - bashrc
        - tmux.conf
      tags:
        - rc

    - name: Copy rc files (root)
      ansible.builtin.template:
        src: ./j2/{{ item }}.j2
        dest: ~/.{{ item }}
        mode: 0644
      loop:
        - vimrc
        - bashrc
        - tmux.conf
      become: true
      become_method: ansible.builtin.sudo
      tags:
        - rc

    - name: Install base packages
      ansible.builtin.dnf:
        name:
          - tmux
          - watch
          - tree
          - python3.11
        state: present
      become: true
      become_method: ansible.builtin.sudo
      tags: package
