---
- hosts: "masters, workers"
  remote_user: kube
  become: yes
  become_method: ansible.builtin.sudo
  become_user: root
  gather_facts: true
  # connection: ssh

  tasks:
    - name: Create containerd configuration file
      ansible.builtin.file:
        path: "/etc/modules-load.d/containerd.conf"
        state: "touch"

    - name: Set up containerd prerequisites
      ansible.builtin.blockinfile:
        path: "/etc/modules-load.d/containerd.conf"
        block: |
          overlay
          br_netfilter

    - name: Load modules
      ansible.builtin.shell: |
        sudo modprobe overlay
        sudo modprobe br_netfilter

    - name: Create network settings configuration file
      ansible.builtin.file:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        state: "touch"

    - name: Set up containerd networking
      ansible.builtin.blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply settings
      ansible.builtin.command: sudo sysctl --system

    - name: Add docker repository
      ansible.builtin.shell: |
        sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        sudo dnf makecache
        sudo dnf install -y containerd.io
        sudo mkdir -p /etc/containerd
        sudo containerd config default | sudo tee /etc/containerd/config.toml
        sudo systemctl restart containerd

    - name: Create k8s repo file
      ansible.builtin.file:
        path: "/etc/yum.repos.d/kubernetes.repo"
        state: "touch"

    - name: Write repository information in the kube repo file
      ansible.builtin.blockinfile:
        path: "/etc/yum.repos.d/kubernetes.repo"
        block: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Install kubernetes
      ansible.builtin.shell: |
        sudo dnf install -y kubelet kubeadm kubectl

    - name: Disable swap
      ansible.builtin.shell: |
        sudo swapoff -a
        sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
