---
# Author: Jose Lima
# Date: 2023-11-02 10:40 CST

- name: "Install microk8s dependencies"
  hosts: microk8s
  # order: shuffle
  gather_facts: false
  become: true
  become_method: ansible.builtin.sudo
  # serial: 10

  tasks:
    - name: "Install repo"
      ansible.builtin.shell: |
        sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y
        sudo dnf upgrade -y

    - name: "Enable extra repos"
      ansible.builtin.shell: |
        sudo subscription-manager repos --enable "rhel-*-optional-rpms" --enable "rhel-*-extras-rpms"
        sudo yum update -y

    - name: Install snapd
      ansible.builtin.yum:
        name: snapd

    - name: Enable snapd
      ansible.builtin.shell: |
        sudo systemctl enable --now snapd.socket
        sudo ln -s /var/lib/snapd/snap /snap

    # - name: Install microk8s
    #   ansible.builtin.shell: |
    #     sudo snap install microk8s --classic
