---
# Author: Jose Lima
# Date: 2023-07-31 18:27 CST

- name: "testing go mod"
  hosts: localhost
  # order: shuffle
  gather_facts: false
  # serial: 10

  tasks:
    - name: "Testing --> "
      go_command:
        command: testing command
        provider:
          username: testname
          password: testpass
      # debugger: always
      register: out

    - name: Debug
      ansible.builtin.debug:
        msg: |
          {{ out.msg }}
