---
#  Author:  Jose Lima (jlima)
#  Date:    2024-01-10 20:08

- name: "test"
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Deploy block
      block:
        - name: Test 1
          ansible.builtin.shell: echo $$
          register: output
          failed_when: true
          ignore_errors: true

        - name: Test 2
          ansible.builtin.shell: echo $$
          register: output
          failed_when: true

        - name: Test 3
          ansible.builtin.shell: echo $$
          register: output

        - name: BUILD PASS
          ansible.builtin.debug:
            msg: |
              {{ output }}
      rescue:
        - name: BUILD FAILED
          ansible.builtin.debug:
            msg: |
              {{ output }}
          failed_when: always
