---
# Author:  Jose Lima (jlima)
# Date:    2024-06-04 15:20

- name: "Test"
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Test workflow
      awx.awx.workflow_launch:
        name: "my workflow template_name"
        controller_host: abc
        controller_username: user
        controller_password: pass
        extra_vars:
          data: [1, 2, 3, 4]
        wait: false
        validate_certs: false
      register: response
