---
# Author: Jose Lima
# Date: 2023-10-20 12:40 CST

- name: "Boot strap new servers"
  hosts: "!localhost,all"
  gather_facts: false
  # serial: 10

  tasks:
    - name: Copy rc files
      ansible.builtin.template:
        src: ./j2/{{ item }}.j2
        dest: ~/.{{ item }}
        mode: 0644
      loop:
        - vimrc
        - bashrc

    - name: Copy rc files (root)
      ansible.builtin.template:
        src: ./j2/{{ item }}.j2
        dest: ~/.{{ item }}
        mode: 0644
      loop:
        - vimrc
        - bashrc
      become: true
      become_method: ansible.builtin.sudo

    - name: Install base packages
      ansible.builtin.dnf:
        name:
          - tmux
          - tree
        state: present
      become: true
      become_method: ansible.builtin.sudo
      tags: package
