---
# Author: Jose Lima
# Date: 2023-10-20 12:40 CST

- name: "Boot strap new servers"
  hosts: "!localhost,all"
  gather_facts: false
  # serial: 10

  tasks:
    - name: Copy rc files
      ansible.builtin.template:
        src: ./j2/{{ item }}.j2
        dest: ~/.{{ item }}
      loop:
        - vimrc
        - bashrc
