[[colors.indexed_colors]]
color = "#ff966c"
index = 16

[[colors.indexed_colors]]
color = "#c53b53"
index = 17

[colors.bright]
black = "#444a73"
blue = "#82aaff"
cyan = "#86e1fc"
green = "#c3e88d"
magenta = "#c099ff"
red = "#ff757f"
white = "#c8d3f5"
yellow = "#ffc777"

[colors.cursor]

# cursor = "#4fc2e8"
cursor = "#cdd6f4"

# text = "#000000"

[colors.normal]
black = "#1b1d2b"
blue = "#82aaff"
cyan = "#86e1fc"
green = "#c3e88d"
magenta = "#c099ff"
red = "#ff757f"
white = "#828bb8"
yellow = "#ffc777"

[colors.primary]
# background = "#0d1e33"
background = "#0e1d2b" # also super nice
foreground = "#c8d3f5"
